version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_goods
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - delivery
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: backend_goods
    restart: always
    ports:
      - "8080:8080"
    networks:
      - delivery
    depends_on:
      postgres:
        condition: service_healthy
    command: "./backend/main -db_url postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB} -log_level ${LOG_LEVEL} -port ${PORT}"

volumes:
  postgres_data:

networks:
  delivery:
    driver: bridge
